### ISSUE TITLE
Why is there no .gemspec?

### ISSUE THREAD

**Issue by sgpinkus** [joshuaavalon/Jekyll-Avalon#1]
Hello.

I want to install this theme, but there is no .gemspec. I thought you needed one of those to install it? I  don't want to just clobber my Jekyll project with the theme, I want to overlay it on my project. I think this is the proper way to use themes no?

**Comment by joshuaavalon** [comment]
I am not a pro in Ruby but I do not see any .gemspec when creating Jekyll theme and I do not know what it is.

If you want overlay it on your project, why don't clone or download it  and overwrite the setting? Or just move your article to the new theme?
 
Then, run
```ruby
bundle install
jekyll serve
```

**Comment by sgpinkus** [comment]
Yeah. Now that I'm more familiar with the Jekyll "theme" landscape it seems there are few people packaging their "themes" as gems. Main reason I object is [SoC](https://en.wikipedia.org/wiki/Separation_of_concerns). But I work with what you have suggested. Ta.
