### ISSUE TITLE
Unclear Instructions

### ISSUE THREAD

**Issue by ghost** [joshuaavalon/Jekyll-Avalon#2]
The instructions are difficult to follow. I suggest add more details and pictures on when to run `bundle install` & `jekyll serve`. It is also unclear when you say it cannot be built by Github. When I try pushing it to a directory it does not show up.

**Comment by joshuaavalon** [comment]
Github only allows certain plugins to be used in Jekyll with gh-pages. If you want still want to use this theme in Github, you have to build in your local machine or find an CI service to do it for you. 

To build in your local machine, you need to have Ruby installed with Jekyll and Bundler (which is the default way to build, you may want to check [Jekyll Official website](https://jekyllrb.com/)).

```
gem install jekyll bundler
```

This will install both of the package for you. Then, navigates to your project directory and run these command.
```
bundle install
jekyll serve
```

After that, a `_site` folder will be generated. Push the  `_site` to your `gh-pages` branch.

If you think this is too much troubles, you may try it in GitLab. A `.gitlab-ci.yml` is included, so it will auto deploy in GitLab.

**Comment by joshuaavalon** [comment]
I will update the instructions. If you still have any questions, you are welcome to ask anything. If there is no further questions, I will close this issue in about a week.
